### ISSUE TITLE
What are the possible choices for Camera?

### ISSUE THREAD

**Issue by mirsaeedi** [gaurav-karna/Ocularis#2]

**Comment by mirsaeedi** [comment]
Since we have chosen Windows IoT core as our operating system #1, we are limited to use Windows supported devices. 
I believe [HD-3000](https://www.amazon.ca/Microsoft-Lifecam-HD-3000-Webcam-Black/) is the cheapest option and it also has a built-in microphone. It's 43 bucks.

The Raspberry Pi official webcam is [Camera Module](https://www.raspberrypi.org/products/camera-module-v2/) which is not supported by Windows IoT Core.

**Comment by mirsaeedi** [comment]
There are some links to it:

1. https://blogs.msdn.microsoft.com/calvin_hsia/2017/04/29/create-a-security-system-with-cameras-on-your-windows-iot-raspberry-pi/

**Comment by gaurav-karna** [comment]
Leaving development aside (where we use webcams), I guess HD-3000 is the best option if it integrates with RPi and IoT.
