### ISSUE TITLE
What are the possible choices for Audio-out?

### ISSUE THREAD

**Issue by mirsaeedi** [gaurav-karna/Ocularis#4]
Raspberry Pi as a built-in audio Jack that we can use. We can connect a headset or a speaker (in the demo).

**Comment by mirsaeedi** [comment]
Raspberry Pi as a built-in audio Jack that we can use. We can connect a headset or a speaker (in the demo).

**Comment by gaurav-karna** [comment]
I think it may be better to use a bluetooth headset with an audio jack receiver. This makes it a bit more efficient and less cumbersome to deal with?
