### ISSUE TITLE
Install Windows IoT on Raspberry Pi 3 B

### ISSUE THREAD

**Issue by mirsaeedi** [gaurav-karna/Ocularis#5]
Install it on the device with a simple hello world application.

**Comment by mirsaeedi** [comment]
I couldn't install the device because it's not compatible with Windows IoT.

However, following links are helpful with installing Windows IoT on RPi 3 B.

1. https://blogs.msdn.microsoft.com/teju_shyamsundar/2016/09/06/windows10iotraspberrypi3/

2. https://docs.microsoft.com/en-us/windows/iot-core/tutorials/quickstarter/devicesetup

**Comment by gaurav-karna** [comment]
We can buy the RPi 3 B if need be!
