### ISSUE TITLE
Buy the required Peripherals

### ISSUE THREAD

**Issue by mirsaeedi** [gaurav-karna/Ocularis#6]
We need to buy these stuffs based on #1 #2 #3 #4 

1. Raspberry Pi 3 B
2. SD Card Class 10+
3. HD-3000

**Comment by mirsaeedi** [comment]
From the above list, I have the first two. We should buy the last one which costs 43 bucks.

**Comment by mirsaeedi** [comment]
I just found that I have Raspberry Pi 3 B+ and Windows IoT is not compatible with that. If we want to get a raspberry we need to get the B one.

**Comment by gaurav-karna** [comment]
No problem! I will share the cost with you.
