### ISSUE TITLE
What are the Intents that we support?

### ISSUE THREAD

**Issue by mirsaeedi** [gaurav-karna/Ocularis#7]
In LUIS terminology intents are the actions or purposes that a user can request in natural language and in different ways. 
Intents are the core of our system. They define the capabilities and limitation of our system.

**Comment by mirsaeedi** [comment]
This list will get updates as we learn more about the potential power of Azure and Windows.

1. What time is it?
2. What Date is today?
3. Where am I?
4. Who are these guys?
5. What's in front of me?
6. Read this text for me.
7. Translate this text for me.

**Comment by gaurav-karna** [comment]
Perhaps we can make the "What's in front of me" perpetual? This way, the system will give live feedback as the user is walking. Then, we can add "Collision Detection" or "Collision Prevention" into the list of features!

**Comment by gaurav-karna** [comment]
Sorry, I didn't mean to close it^
